$ErrorActionPreference = "Stop"

# Configuration
$AppName = "Remote FS Client"
$AppVersion = "0.1.0"
$AppExeName = "remote_fs_client.exe"
$OutputBaseFilename = "remote_fs_installer"

# Check if ISCC is in the PATH (GitHub Actions does this)
if (Get-Command "ISCC" -ErrorAction SilentlyContinue) {
    $InnoSetupCompiler = "ISCC"
    Write-Host "Found Inno Setup in PATH." -ForegroundColor Green
} else {
    Write-Error "Could not find Inno Setup (ISCC.exe). Please install it (https://github.com/jrsoftware/issrc/releases/latest) and add it to your PATH."
    exit 1
}

$ProjectRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\..\.."))
# Navigate to Project Root
Set-Location -Path $ProjectRoot

# Build the Rust Project in Release Mode
Write-Host "[INFO] Building Rust Project (Release)..." -ForegroundColor Cyan
cargo build --release --bin client
if ($LASTEXITCODE -ne 0) { exit 1 }

# Prepare Directories for Build Directory and Installer
$BuildDir = [System.IO.Path]::GetFullPath((Join-Path $ProjectRoot "build_output\windows"))
if (-not (Test-Path $BuildDir)) { 
    New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null 
}

# Copy files to Build Directory
Write-Host "[INFO] Gathering Files..." -ForegroundColor Cyan
$ExeSource =  [System.IO.Path]::GetFullPath((Join-Path $ProjectRoot "target\release\client.exe"))
$ExeDest =  [System.IO.Path]::GetFullPath((Join-Path $BuildDir $AppExeName))
Copy-Item -Path $ExeSource -Destination $ExeDest -Force

# Define WinFsp Repo
$Repo = "winfsp/winfsp"
# Get the Latest Release Info from GitHub API
$ApiUrl = "https://api.github.com/repos/$Repo/releases/latest"
$LatestRelease = Invoke-RestMethod -Uri $ApiUrl
# Find the asset you want (e.g., the MSI or your EXE)
# This filters the assets list to find one ending in .msi
$WinFspAsset = $LatestRelease.assets | Where-Object { $_.name -like "*.msi" }

$WinFspUrl = $WinFspAsset | Select-Object -ExpandProperty browser_download_url
$MsiName = $WinFspAsset.name
$MsiDest = Join-Path $BuildDir $MsiName

# Download WinFsp MSI if not present
if (-not (Test-Path $MsiDest)) {
    # Download it
    Write-Host "[INFO] Downloading WinFsp MSI..." -ForegroundColor Yellow
    Invoke-WebRequest -Uri $WinFspUrl -OutFile $MsiDest
    Write-Host "Downloaded version: $($LatestRelease.tag_name)"
} else {
    Write-Host "[INFO] WinFsp MSI already exists (skipping download)." -ForegroundColor Gray
}

# Copy Icon File
$IconPath = Join-Path $PSScriptRoot "icon.ico"
if (Test-Path $IconPath) {
    $Icon = (Join-Path $BuildDir "icon.ico")
    Copy-Item -Path $IconPath -Destination $Icon -Force
    Write-Host "[INFO] Icon file copied." -ForegroundColor Green
} else {
    $Icon = ""
    Write-Host "[WARNING] Icon file not found at $IconPath. The installer will use a default icon." -ForegroundColor Yellow
}

# Generate Inno Setup script on the fly
Write-Host "[INFO] Generating Installer Script..." -ForegroundColor Cyan
$IssPath = Join-Path $BuildDir "setup_script.iss"

$InnoScript = @"
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "$AppName"
#define MyAppVersion "$AppVersion"
; #define MyAppPublisher "My Company, Inc."
; #define MyAppURL "https://www.example.com/"
#define MyAppExeName "$AppExeName"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{01DFCCF3-D28E-444F-A162-84DC76F038C6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
; AppPublisher={#MyAppPublisher}
; AppPublisherURL={#MyAppURL}
; AppSupportURL={#MyAppURL}
; AppUpdatesURL={#MyAppURL}

; DefaultDirName={autopf}\{#MyAppName}
DefaultDirName={userpf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoVersion={#MyAppVersion}
VersionInfoDescription=Remote Filesystem Client Installer

; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible

DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; LicenseFile=path_to_file
; InfoBeforeFile=path_to_file
; InfoAfterFile=path_to_file

; Remove the following line to run in administrative install mode (install for all users).
; PrivilegesRequired=lowest

ChangesEnvironment=yes

OutputBaseFilename=$OutputBaseFilename
OutputDir=$BuildDir
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
#if FileExists("$Icon")
  Source: "$Icon"; DestDir: "{app}"; Flags: ignoreversion
#endif
Source: "$MsiDest"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "$BuildDir\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; \
  Filename: "{app}\{#MyAppExeName}"; \
  IconFilename: "{app}\icon.ico"; \
  Parameters: "{code:GetParams}"; \
  WorkingDir: "{app}"

Name: "{autodesktop}\{#MyAppName}"; \
  Filename: "{app}\{#MyAppExeName}"; \
  Parameters: "{code:GetParams}"; \
  WorkingDir: "{app}"; \
  IconFilename: "{app}\icon.ico"; \
  Tasks: desktopicon

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
  ValueType: expandsz; ValueName: "Path"; \
  ValueData: "{olddata};C:\Program Files (x86)\WinFsp\bin"; \
  Check: NeedsWinFspPath

; Root: HKCU; Subkey: "Environment"; \
;   ValueType: expandsz; ValueName: "Path"; \
;   ValueData: "{olddata};C:\Program Files (x86)\WinFsp\bin"; \
;   Check: NeedsWinFspPathUser

[Run]
; Install WinFsp
Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\$MsiName"" /qn /norestart"; \
  StatusMsg: "Installing File System Driver..."; \
  Check: NeedWinFsp

; ; Launch App
; Filename: "{app}\{#MyAppExeName}"; \
;   Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; \
;   Parameters: "{code:GetParams}"; \
;   Flags: nowait postinstall skipifsilent

[Code]
var
  ConfigPage: TInputQueryWizardPage;

// Create the Custom Configuration Page
procedure InitializeWizard;
begin
  ConfigPage := CreateInputQueryPage(wpWelcome,
    'Connection Configuration', 'Server Details',
    'Please enter the connection details for your Remote FS.');

  ConfigPage.Add('Server URL:', False);
  
  // Set Defaults
  ConfigPage.Values[0] := 'http://localhost:8080';
end;

// Build the Command Line Arguments
function GetParams(Param: String): String;
begin
  // format: run --server-url "URL"
  Result := 'run --server-url "' + ConfigPage.Values[0];
end;

// Check for WinFsp
function NeedWinFsp: Boolean;
begin
  Result := not FileExists(ExpandConstant('{commonpf64}\WinFsp\bin\winfsp-x64.dll'));
end;

// Check Env Path System
function NeedsWinFspPath: Boolean;
var
  OrigPath: String;
begin
  // Try to read the SYSTEM 'Path' variable
  if RegQueryStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', OrigPath) then
    // It exists, so check if our folder is already in it
    Result := Pos('WinFsp\bin', OrigPath) = 0
  else
    Result := True;
end;

function NeedsWinFspPathUser: Boolean;
var
  OrigPath: String;
begin
  // Try to read the CURRENT USER 'Path' variable
  if RegQueryStringValue(HKCU, 'Environment', 'Path', OrigPath) then
    // It exists, so check if our folder is already in it
    Result := Pos('WinFsp\bin', OrigPath) = 0
  else
    Result := True
end;

[UninstallDelete]
Type: filesandordirs; Name: "{app}\logs"
"@

Set-Content -Path $IssPath -Value $InnoScript

# Compile Installer using Inno Setup Compiler
Write-Host "[INFO] Compiling Installer..." -ForegroundColor Cyan
& $InnoSetupCompiler $IssPath | Out-Null

if ($LASTEXITCODE -eq 0) {
    Write-Host "[SUCCESS] Installer created at: $BuildDir\$OutputBaseFilename.exe" -ForegroundColor Green
} else {
    Write-Error "[ERROR] Inno Setup compilation failed."
}