x-constants:
  app_path: &app_path ${APP_PATH}
  mount_point: &mount_point ${MOUNT_POINT}
  fs_root: &fs_root ${FS_ROOT}
  server_url: &server_url http://${SERVER_HOST:-server}:${SERVER_PORT}
  log_targets: &log_targets ${LOG_TARGETS:-all}
  log_format: &log_format ${LOG_FORMAT:-full}
  log_level: &log_level ${LOG_LEVEL:-info}
  log_path: &log_path ${LOG_PATH:-logs}
  log_file: &log_file ${LOG_FILE:-remote_fs}
  log_rotation: &log_rotation ${LOG_ROTATION:-never}

services:
  server:
    build:
      context: ./server
      args:
        app_path: *app_path
        remote_fs_server: server # the name of the package
    container_name: remote_fs-server
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - remote_fs_data:${FS_ROOT}
    environment:
      SERVER_HOST: ${SERVER_HOST:-server}
      SERVER_PORT: ${SERVER_PORT}
      FS_ROOT: *fs_root
      LOG_TARGETS: *log_targets
      LOG_FORMAT: *log_format
      LOG_LEVEL: *log_level
      LOG_PATH: *log_path
      LOG_FILE: *log_file
      LOG_ROTATION: *log_rotation
    networks:
      - remote-fs-net

  client:
    build:
      context: ./client
      args:
        app_path: *app_path
        remote_fs_client: client # the name of the package
    container_name: remote_fs-client
    # privileged: true
    # network: host # in case X11 does not work properly
    networks:
      - remote-fs-net
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    depends_on:
      - server
    environment:
      MOUNT_POINT: *mount_point
      SERVER_URL: *server_url
      LOG_TARGETS: *log_targets
      LOG_FORMAT: *log_format
      LOG_LEVEL: *log_level
      LOG_PATH: *log_path
      LOG_FILE: *log_file
      LOG_ROTATION: *log_rotation
      DISPLAY: ${DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      SLINT_BACKEND: software
      WINIT_UNIX_BACKEND: x11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
    # command: >
    #   --mountpoint ${MOUNT_POINT} --server-url http://server:8080/api
    tty: true # Keep the terminal open
    entrypoint: [ "/bin/bash" ]

  develop:
    develop:
    image: rust:slim
    container_name: remote_fs-develop
    network_mode: host      # <--- Aggiunto per vedere WSLg (:0)
    ipc: host               # <--- Aggiunto per la memoria condivisa X11
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - SLINT_BACKEND=software
      - WINIT_UNIX_BACKEND=x11
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:${APP_PATH}/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
    working_dir: *app_path
    tty: true

volumes:
  remote_fs_data:

networks:
  remote-fs-net:
