x-constants:
  mount_point: &mount_point ${RFS__MOUNT_POINT}
  server_url: &server_url ${RFS__SERVER_URL:-http://${RFS__SERVER_HOST:-server}:${RFS__SERVER_PORT:-8080}}
  database_path: &database_path ${DATABASE_PATH:-database/db.sqlite}

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
      args:
        bin_name: server # the name of the package
    container_name: remote_fs-server
    ports:
      - "${RFS__SERVER_PORT:-8080}:8080"
    volumes:
      - remote_fs_data:${RFS__FILESYSTEM_ROOT}
    environment:
      RFS__SERVER_HOST: ${RFS__SERVER_HOST:-server}
      RFS__SERVER_PORT: ${RFS__SERVER_PORT:-8080}
      RFS__FILESYSTEM_ROOT: ${RFS__FILESYSTEM_ROOT}
      DATABASE_PATH: *database_path
    networks:
      - remote-fs-net
    env_file:
      - server/.env
    command: >
      --database-path ${DATABASE_PATH} run --filesystem-root ${RFS__FILESYSTEM_ROOT} --server-host ${RFS__SERVER_HOST} --server-port ${RFS__SERVER_PORT}

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
      args:
        bin_name: client # the name of the package
    container_name: remote_fs-client
    # privileged: true
    networks:
      - remote-fs-net
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    depends_on:
      - server
    environment:
      RFS__MOUNT_POINT: *mount_point
      RFS__SERVER_URL: *server_url
    env_file:
      - client/.env
    # command: >
    #   run --mount-point ${RFS__MOUNT_POINT} --server-url ${RFS__SERVER_URL}
    tty: true # Keep the terminal open
    entrypoint: [ "/bin/bash" ]

  develop:
    image: rust:slim
    container_name: remote_fs-develop
    # privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    networks:
      - remote-fs-net
    volumes:
      - .:${APP_PATH}/
      # - ./mount_dir:${RFS__FILESYSTEM_ROOT} # Server FS root for testing purposes
    working_dir: ${APP_PATH}
    tty: true # Keep the terminal open
    restart: unless-stopped # Automatically restart unless stopped manually

volumes:
  remote_fs_data:


networks:
  remote-fs-net:
